### ISSUE TITLE
The last visited step is set to incomplete when going to some earlier step

### ISSUE THREAD

**Issue by rsiebeling** [mgonto/angular-wizard#169] opened 2016-02-26 14:50 UTC
When I have a wizard with 4 steps and I am in step 3 and going back to step 2 then step 3 is disabled and I have to complete step two again in order to enabled step 3.

I find this strange because to come to step 3 I already had completed step 2, so when I go back to step 2  from step 3 I expect that I am able to go to step 3 again, but this is not possible.

**Comment by jacobscarter** [comment] 2016-04-21 15:42
Duplicate of issue #158 this will be addressed in the next release, thanks for your input.

**Closed by jacobscarter** 2016-04-21 15:42 UTC
Labels: duplicate, enhancement

**Comment by mparramont** [comment] 2018-05-07 13:08
FYI, I have implemented this in #270.
