### ISSUE TITLE
Remove dependency for lodash.js

### ISSUE THREAD

**Issue by shijukbabu** [mgonto/angular-wizard#116] opened 2015-07-27 08:41 UTC
When I dont import lodash.js I get the following error

<pre>
ReferenceError: _ is not defined
    at Object.fn (angular-wizard.js:103)
    at Scope.$get.Scope.$digest (angular.js:15685)
    at Scope.$get.Scope.$apply (angular.js:15953)
    at done (angular.js:10366)
    at completeRequest (angular.js:10538)
    at XMLHttpRequest.requestLoaded (angular.js:10479)
</pre>
I'm using AngularJS 1.4.2 and latest version of angular-wizard - 0.5.3
I don't want to add more dependencies to my project. How to solve it?

**Comment by rafaelfragosom** [comment] 2015-07-28 01:31
@shijukbabu I'm not sure if I follow your question... because every dependency you add to your project comes with more dependencies... it's kinda inevitable.

Regarding your error, by the logic, lodash is missing from angular-wizard dependencies as you pointed, can you tell me the steps to reproduce this error?

**Comment by shijukbabu** [comment] 2015-07-28 09:02
Just remove the dependency for lodash. You will get this error. I understand I need to import lodash. I just asking if I don't want to use lodash how to change the script?

**Comment by rafaelfragosom** [comment] 2015-07-28 13:49
@shijukbabu If you look at the source code, the whole script's using lodash. Maybe @mgonto could extract the lodash methods he's using and make them JS native?

But anyways, lodash is so helpful and fast, even faster than native JS in some cases. You could definitely use it in your advantage.

**Comment by shijukbabu** [comment] 2015-07-28 15:46
I was just thinking of a directory which is not much depend on other libraries. So I asked. It's fine anyway.

Also it's not mentioned in the README that it depends on lodash. I didn't understand why it was not working. And Google for errors. Then I had to check the demo page and checked using view source code. Will be better if it's mentioned. So nobody will be confused. :smile:

**Comment by rafaelfragosom** [comment] 2015-07-28 17:55
@shijukbabu Agreed, but you can always read the source code or at least the `bower.json` or `package.json`. I'm here to help.

**Comment by jacobscarter** [comment] 2015-08-04 16:17
There is a pull request from a while ago that removed lodash since we are only using it for one method.  I will merge that PR as soon as I can and this wont happen again in the future.

Thanks.

**Comment by redhead** [comment] 2015-11-04 12:38
What's the status of this issue? We would love to get rid of lodash all together.

**Comment by tymat** [comment] 2015-12-24 10:55
Thanks.

**Comment by jacobscarter** [comment] 2015-12-25 07:40
This has been added and will be in the next push

**Closed by jacobscarter** 2015-12-25 07:40 UTC
Labels: enhancement
